apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deployment
  labels:
    app: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: stanleywbwong/audit
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.96.0.100
